products:
  newest_products_number: 4
  load_products_number: 4
  products_per_page: 12
  min_from_price: 0
  min_to_price: 0
  comment_per_page: 10
ratings:
  min_rate: 1
  max_rate: 5
  round: 2
carts:
  min_amount: 1
orders:
  min_quantity: 1
  amount_round: 2
users:
  order_per_page: 10
product_suggests:
  product_suggest_per_page: 10
